[build]
  base = "client"
  command = "npm ci --legacy-peer-deps --no-audit --prefer-offline || npm install --legacy-peer-deps --no-audit && npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-audit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
